version: '3'
services:
  backend:
    container_name: shortlink-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '25000:3000'
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  db:
    image: 'mysql:8.0.32'
    container_name: shortlink-db
    ports:
      - '$DB_PORT:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_ROOT_PASSWORD
      - MYSQL_DATABASE=$DB_NAME
    volumes:
      - ./db:/var/lib/mysql
    healthcheck:
      test:
        [
          'CMD',
          'mysqladmin',
          'ping',
          '-h',
          'localhost',
          '-u',
          'root',
          '-p$MYSQL_ROOT_PASSWORD',
        ]
      timeout: 20s
      retries: 10
