services:
  backend:
    container_name: shortlink-backend
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - TZ=Asia/Seoul
    ports:
      - '${BACKEND_PORT}:${BACKEND_DOCKER_PORT}'
    depends_on:
      db:
        condition: service_healthy

  db:
    image: 'mysql:8.0.39'
    container_name: shortlink-db
    ports:
      - '${DB_PORT}:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - TZ=Asia/Seoul
    volumes:
      - ./db:/var/lib/mysql
    healthcheck:
      test:
        [
          'CMD',
          'mysqladmin',
          'ping',
          '-h',
          'localhost',
          '-u',
          'root',
          '-p$MYSQL_ROOT_PASSWORD',
        ]
      timeout: 3s
      retries: 10
      interval: 3s
